#!/usr/bin/env perl

use strict;
use warnings;
use autodie;
use feature qw(say);

use Text::CSV;
use XML::Feed;
use URI;
use LWP::Protocol::https;
use File::Slurp qw(write_file);
use Fcntl qw(:flock);
use Encode qw(encode_utf8);
use IO::Handle ();

STDOUT->autoflush(1);
STDERR->autoflush(1);

my $work_dir = 'work';

my $csv_file = 'feeds.csv';
my $csv_feed_url_column = 'feed_url';
my $csv_id_column       = 'md5';

chdir $work_dir;
my @contributors = get_contributors_from_csv();
download_feeds(@contributors);
exit;

############################

sub get_contributors_from_csv {
    say "Extracting contributors from $csv_file...";
    my $csv = Text::CSV->new({
        'sep_char' => ';',
        'auto_diag' => 1,
        'binary' => 1,
    });
    open my $csv_fh, '<', $csv_file;
    flock($csv_fh, LOCK_SH);
    my @columns = @{ $csv->getline($csv_fh) };
    $csv->column_names(@columns);
    my @contributors;
    while ( my $row = $csv->getline_hr($csv_fh) ) {
        push @contributors, {
            'feed_url' => $row->{ $csv_feed_url_column },
            'id'       => $row->{ $csv_id_column       },
        };
    }
    flock($csv_fh, LOCK_UN);
    close $csv_fh;
    return @contributors;
}

sub download_feeds {
    my (@contributors) = @_;
    say "Downloading feeds...";
    my @feeds;
    while ( my $contributor = shift @contributors) {
        my $feed_url = $contributor->{'feed_url'};
        my $id       = $contributor->{'id'};
        next unless $feed_url;
        next unless $id;
        say "Downloading $feed_url...";
        my $feed = eval { XML::Feed->parse( URI->new($feed_url) ); };
        warn "Unable to parse feed: $@" if $@;
        next if $@;
        say "\tUnable to find $feed_url" unless $feed;
        say "\tError occured: " . XML::Feed->error if XML::Feed->error;
        next unless $feed;
        # $feed->title docs doesn't say if it returns character or byte string
        my $title = $feed->title;
        # Make sure it is always bytes
        $title = encode_utf8($title) if utf8::is_utf8($title);
        say "\tTitle: " . $title . " (" . $feed->format . ")";
        say "\tSaving to file: $id.xml";
        my $feed_xml = eval { $feed->as_xml; };
        warn "Unable to convert feed to XML: $@" if $@;
        next if $@;
        my $binmode = utf8::is_utf8($feed_xml) ? ":encoding(UTF-8)" : ":raw";
        write_file( "$id.xml", { binmode => $binmode, atomic => 1 }, $feed_xml );
    }
}
